version: '3.7'

services:
  bank_web:
    build:
      context: ./rasta_problem_bank
      dockerfile: Dockerfile.prod
    command: sh -c "python3 manage.py migrate && gunicorn rasta_problem_bank.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - bank_static_volume:/usr/src/app/staticfiles
      - bank_media_volume:/usr/src/app/media
      - ./app/logging:/usr/src/app/logging
    env_file:
      - ./.env.prod
    depends_on:
      - bank_db
        
  bank_db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: 
        context: ./
        dockerfile: nginx/Dockerfile
    restart: always
    volumes:
      - bank_static_volume:/home/app/bank_staticfiles
      - bank_media_volume:/home/app/bank_media
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - bank_web
volumes:
  bank_static_volume:
  bank_media_volume:
  postgres_data:
