version: '3.7'

services:
  web:
    build:
      context: ./../rasta_problem_bank
      dockerfile: ./Dockerfile.prod
    command: gunicorn ra.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/logging:/usr/src/app/logging
    env_file:
      - ./.env.prod
