version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: ./../rasta_problem_bank/Dockerfile.prod
    command: gunicorn ra.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/logging:/usr/src/app/logging
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: sqlite:12.0-alpine
    volumes:
      - sqlite_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - web
  volumes:
  sqlite_data:
