version: '3.7'

services:
  bank_web:
    build:
      context: ./../rasta_problem_bank
      dockerfile: ./Dockerfile.prod
    ports:
      - "8000:8000"
    command: pipenv --python 3.7.4 run gunicorn rasta_problem_bank.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - bank_static_volume:/usr/src/app/staticfiles
      - bank_media_volume:/usr/src/app/media
      - ./app/logging:/usr/src/app/logging
    env_file:
      - ./.env.prod
      
  bank_react:
    build:
      context: ./../rasta_problem_bank_ui
      dockerfile: ./Dockerfile.prod
    volumes:
      - bank_react_files:/app/build
    env_file:
      - ./.env.prod.react
        
  bank_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - bank_static_volume:/home/app/bank_staticfiles
      - bank_media_volume:/home/app/bank_media
      - ./log/nginx:/var/log/nginx
      - bank_react_files:/home/app/bank_build
    ports:
      - 80:80
    depends_on:
      - bank_web
volumes:
  bank_static_volume:
  bank_media_volume:
  postgres_data:
  bank_react_files:
